name: CI/CD on Release

on:
  push:
    branches:
      - release

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 14

      - name: Install dependencies
        run: npm install

      - name: Build
        run: npm run build

  deploy:
    runs-on: ubuntu-latest

    needs: build

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup SSH
        run: |
          mkdir -p ~/.ssh
          echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -t rsa 43.136.121.202 >> ~/.ssh/known_hosts

      - name: Deploy to Server
        run: |
          rsync -r --delete-after $GITHUB_WORKSPACE/dist/ ubuntu@43.136.121.202:~/github-dist/
        env:
          SSH_PRIVATE_KEY: ${{ secrets.mac }}
